---

server:
  port: 8081
  contextPath: "/sa"


service:
  b:
    url: "http://service-b:8082/sb/info"
    method: "post"

app:
  version: v1

spring:
  sleuth:
    sampler:
      percentage: "1.0"
  zipkin:
    base-url: http://10.1.104.231:30081